# Meta Data for SEO

## Homepage
title = "CONX Docs"
titleSeparator = "|"
titleAddition = ""
description = "CONX Chain Technical Documentation"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["xpla-opengraph-image.svg"]
ogLocale = "en_US"
domainTLD = "docs.xpla.io"
titleHome = "CONX Docs"

## Twitter Cards
twitterSite = ""
twitterCreator = ""

## JSON-LD
# schemaType = "Person"
schemaType = ""
schemaName = ""
schemaAuthor = ""
schemaAuthorTwitter = ""
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = ""
schemaLocale = ""
schemaLogo = ""
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = ""
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = ""
schemaSection = ""

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a href=\"https://xpla.io/\" style=\"display: inline-block; vertical-align: middle;\"><div class=\"xpla_logo\"></div></a>"

# Feed
copyRight = "Copyright (c) 2021-2022 XPLA"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = ""

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/xpladev/docs"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = false

[sections]
  sectionNav = ["learn", "develop", "full-node", "guide", "ecosystem"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
# searchSectionsIndex = []
  searchSectionsIndex = "ALL"
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1
  navButtonInSection = true
  disableHeaderBar = true
  alternativeHome = "/learn/learn/about-xpla-chain/"

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
